### ISSUE TITLE
childViewController does not support UITableViewController

### ISSUE THREAD

**Issue by NikoTung** [Yelp/YLTableView#12]
It seem that if the `childViewController` is kind of UITableViewController then the height of cell is wrong .And Xcode will output the following log

    Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a tableview cell's content view. We're considering the collapse unintentional and using standard height instead.

Constraints of `childViewController ` can't not get the height,because the childViewController's height is determined by the tableView which is determined by the content size .

**Comment by benasher44** [comment]
@NikoTung in general, if you try to have a view's size be determined by its subview and that subview is a UIScrollView (in this case the UITableViewController's view is a UITableView which is a UIScrollView), you're going to run into this issue. You can't use a UIScrollView to determine the size of its superview, since the whole idea of a UIScrollView is to be able to contain an unbounded amount of content regardless of how much room the UIScrollView is allowed to occupy. Does this make sense?

The way I see it, the main option you have here is to add a constraint to constrain the childViewController's view to a specific height.

**Comment by benasher44** [comment]
@NikoTung hope this suggestion was helpful! I'm going to close this, since this is a general limitation of embedding a UIScrollView in a UITableViewCell.
