### ISSUE TITLE
Inefficient cells configuration in `tableView:cellForRowAtIndexPath:`

### ISSUE THREAD

**Issue by tomassliz** [Yelp/YLTableView#4]
If you read [great post](https://medium.com/ios-os-x-development/perfect-smooth-scrolling-in-uitableviews-fd609d5275a5) from @plasm_lc then you will find that method `tableView:cellForRowAtIndexPath:` is not a good place for configuring cells. Better place is method `tableView:willDisplayCell:forRowAtIndexPath:`. It's more efficient and recommended by Apple in official documentation.

**Comment by benasher44** [comment]
Hi @tomassliz! The reason that we do cell configuration in ```tableView:cellForRowAtIndexPath:``` is so that each cell can have enough information to determine its size properly before UITableView attempts to size each cell. By the time ```tableView:willDisplayCell:forRowAtIndexPath:``` has been called, the UITableView instance has already determined the height for the cell that is going to be displayed. YLTableView is somewhat geared towards using Auto Layout, and taking an Auto Layout-leaning approach to UITableViewCell sizing and layout requires that the data be setup in each cell before UITableView attempts to determine the height of the cell. Auto Layout requires that you have constraints on views that contain the data required to size those views, and those views need to be constrained to a superview. While the article you linked takes the approach of doing the sizing in a model, so as to avoid setting data on the cell ahead of time, this is really difficult to do if you want to use Auto Layout.
